repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
    name: Check for added large files
    description: Prevent giant files from being committed
    entry: check-added-large-files
    language: python
  - id: check-ast
    name: Check python ast
    description: Simply check whether the files parse as valid python.
    entry: check-ast
    language: python
    types: [python]
  - id: check-executables-have-shebangs
    name: Check that executables have shebangs
    description: Ensures that (non-binary) executables have a shebang.
    entry: check-executables-have-shebangs
    language: python
    types: [text, executable]
    stages: [commit, push, manual]
  - id: check-json
    name: Check JSON
    description: This hook checks json files for parseable syntax.
    entry: check-json
    language: python
    types: [json]
  - id: pretty-format-json
    name: Pretty format JSON
    description: This hook sets a standard for formatting JSON files.
    entry: pretty-format-json
    language: python
    types: [json]
  - id: check-yaml
    name: Check Yaml
    description: This hook checks yaml files for parseable syntax.
    entry: check-yaml
    language: python
    types: [yaml]
  - id: detect-private-key
    name: Detect Private Key
    description: Detects the presence of private keys
    entry: detect-private-key
    language: python
    types: [text]
  - id: double-quote-string-fixer
    name: Fix double quoted strings
    description: This hook replaces double quoted strings with single quoted strings
    entry: double-quote-string-fixer
    language: python
    types: [python]
  - id: end-of-file-fixer
    name: Fix End of Files
    description: Ensures that a file is either empty, or ends with one newline.
    entry: end-of-file-fixer
    language: python
    types: [text]
    stages: [commit, push, manual]
    # - id: no-commit-to-branch
    #   name: "Don't commit to branch"
    #   entry: no-commit-to-branch
    #   language: python
    #   pass_filenames: false
    #   always_run: true
  - id: requirements-txt-fixer
    name: Fix requirements.txt
    description: Sorts entries in requirements.txt
    entry: requirements-txt-fixer
    language: python
    files: requirements.*\.txt$
  - id: sort-simple-yaml
    name: Sort simple YAML files
    language: python
    entry: sort-simple-yaml
    description: Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks.
    files: '^$'
  - id: trailing-whitespace
    name: Trim Trailing Whitespace
    description: This hook trims trailing whitespace.
    entry: trailing-whitespace-fixer
    language: python
    types: [text]
    stages: [commit, push, manual]
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.2.0rc1
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
# - repo: git@github.com:sjmiller609/baremetal_kube.git
#   rev: cbf9c274147efd9492875f9653eae672983a2491
#   hooks:
#     - id: ansible-run
