- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
    name: Trim Trailing Whitespace
    description: This hook trims trailing whitespace.
    entry: trailing-whitespace-fixer
    language: python
    types: [text]
    stages: [commit, push, manual]
- repo: https://github.com/ansible/ansible-lint.git
  rev: v3.5.1
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
