---
- hosts: routers
  gather_facts: false
  tasks:
  - name: Check for three interfaces
    edgeos_command:
      commands: show interfaces ethernet {{ item }}
    loop:
      - eth0
      - eth1
      - eth2
  - name: Configure ingress firewall
    edgeos_command:
      commands:
        - configure
        # Ingress to internal network
        - set firewall name WAN_IN default-action drop
        - set firewall name WAN_IN description 'WAN to internal network'
        - set firewall name WAN_IN rule 10 action accept
        - set firewall name WAN_IN rule 10 description 'Allow established/related'
        - set firewall name WAN_IN rule 10 state established enable
        - set firewall name WAN_IN rule 10 state related enable
        - set firewall name WAN_IN rule 20 action drop
        - set firewall name WAN_IN rule 20 description 'Drop invalid state'
        - set firewall name WAN_IN rule 20 state invalid enable
        # Ingress to the router itself
        - set firewall name WAN_LOCAL default-action drop
        - set firewall name WAN_LOCAL description 'WAN to router'
        - set firewall name WAN_LOCAL rule 10 action accept
        - set firewall name WAN_LOCAL rule 10 description 'Allow established/related'
        - set firewall name WAN_LOCAL rule 10 state established enable
        - set firewall name WAN_LOCAL rule 10 state related enable
        - set firewall name WAN_LOCAL rule 20 action drop
        - set firewall name WAN_LOCAL rule 20 description 'Drop invalid state'
        - set firewall name WAN_LOCAL rule 20 state invalid enable
        # Connect to eth2
        - set interfaces ethernet eth2 firewall in name WAN_IN
        - set interfaces ethernet eth2 firewall local name WAN_LOCAL
        # Save
        - commit
        - save
