---

- hosts: routers
  roles:
    - edgeos

- hosts: localhost
  become: yes
  roles:
    - pxe-server

- name: Include Kubespray tasks
  import_playbook: kubespray/cluster.yml

# - name: Install MetalLB
#   import_playbook: kubespray/contrib/metallb/metallb.yml
