---

- hosts: localhost
  gather_facts: true
  tasks:
    - debug:
        msg: "{{ hostvars['localhost']['ansible_default_ipv4']['address'] }}"

- hosts: routers
  roles:
    - edgeos

- hosts: localhost
  become: yes
  roles:
    - pxe-server


- name: Include Kubespray tasks
  import_playbook: kubespray/cluster.yml

# - name: Install MetalLB
#   import_playbook: kubespray/contrib/metallb/metallb.yml
