---

- hosts: localhost
  gather_facts: true
  tasks:
    - debug:
        msg: "{{ hostvars['localhost']['ansible_default_ipv4']['address'] }}"

- hosts: routers
  roles:
    - edgeos

- hosts: localhost
  become: yes
  roles:
    - pxe-server

- name: Include Kubespray tasks
  include: kubespray/cluster.yml
