---
# tasks file for pxe-server
#
- name: System details
  debug: msg="{{ item }}"
  with_items:
  - "{{ ansible_distribution }}"
  - "{{ ansible_distribution_version }}"
  - "{{ ansible_distribution_major_version }}"

- name: Check distribution is Ubuntu
  assert:
    that: ansible_distribution == "Ubuntu"

- name: Check distribution major version is 18
  assert:
    that: ansible_distribution_major_version == "18"

- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name:
      # - isc-dhcp-server
      - tftpd-hpa
      - syslinux
      - pxelinux
      - nfs-kernel-server
      - initramfs-tools
    state: present

- name: 'Configure TFTP: configure server'
  become: yes
  copy:
    src: tftpd-hpa
    dest: /etc/default/tftpd-hp
    owner: root
    group: root
    mode: '0644'

- name: 'Configure TFTP: create root directory structure'
  become: yes
  file:
    path: "/tftpboot/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0744'
  with_items:
    - pxelinux.cfg
    - boot

# better than 'copy' directive because copy would
# not work when not using localhost target.
# also, this is much faster
- name: 'Configure TFTP: pxelinux.0 and isolinux'
  become: yes
  shell: |
    set -xe
    rm /tftpboot/pxelinux.0 || true
    rm -rf /tftpboot/boot/isolinux || true
    cp /usr/lib/PXELINUX/pxelinux.0 /tftpboot
    cp -r /usr/lib/syslinux/modules/bios /tftpboot/boot/isolinux

- name: 'Configure TFTP: pxelinux.cfg'
  become: yes
  copy:
    src: pxelinux.cfg
    dest: /tftpboot/pxelinux.cfg/default
    owner: root
    group: root
    mode: '0644'

- name: Start service tftpd-hpa
  become: yes
  service:
    name: tftpd-hpa
    state: started
